### ISSUE TITLE
Create a skeleton node service for Identity

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/catalogue#1276] opened 2021-01-15 17:18 UTC
We should create a skeleton node service using our infrastructure modules and front-end patterns, that can be deployed as a separate project.

This service should follow the existing pattern and be available on the subdomain "http://identity.wellcomecollection.org/" and it's stage equivalent, and be redirected to from a path prefix as with content & catalogue.

In order to allow Digirati developers sufficient autonomy we should create a new Buildkite pipeline to build & deploy "identity", but still with automated stage deployment and gated prod deployment. 

It should provide a simple hello-world implementation of a new app in the same style as content & catalogue, but named "identity".

**Comment by jamesgorrie** [comment] 2021-01-21 14:40
Dupe of [this](https://github.com/wellcomecollection/platform/issues/4984)?

**Closed** 2021-01-25 11:18 UTC
