### ISSUE TITLE
Add top level archive collections in search results

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/catalogue#741] opened 2020-08-10 09:36 UTC
As a way for users to find and explore collections, we want to add top level collections to the search results.

We can do this quite easily by just adding [`archive-collection`](https://api.wellcomecollection.org/catalogue/v2/works?workType=archive-collection) to the list of current `workType`s we allow through.

This would add `1173` results to the list, which is insignificant in terms of affecting the tf/idf.

We will be adding and working via the rank_eval tests to ensure they don't skew the current query.

The main issue however that we also have the filter of `items.locations.locationType=iiif-image,iiif-presentation` which none of the `archive-collection`s have, so they will not be returned. 

Ping @harrisonpim @alicerichmond @taceybadgerbrook

**Comment by harrisonpim** [comment] 2020-08-10 11:44
plenty of examples of people searching for things that look like archives in the search logs. from the last couple of weeks we've got:
- WH/HMM
- WA/HMM/CM
- NAVAL AND MILITARY RAMC 1856/1
- EPB 20057/B/1
- PP/KEB/E/6/1
- RAI/40/2/29
- St Bartholomew's Hospital Archives & Museum
- Eugenics Society Archive
- creators:"St Bartholomew\'s Hospital Archives"
- archives
- WELLCOME FOUNDATION ARCHIVE
- Wellcome archive

**Comment by pollecuttn** [comment] 2020-08-19 14:22
Closing as dupe of https://github.com/wellcomecollection/wellcomecollection.org/issues/5366

**Closed by pollecuttn** 2020-08-19 14:22 UTC
